### PR TITLE
Reset Password UI added and integrated 

### LINKED ISSUE #23: Login and logout integration
Integrate login API([link](https://github.com/SPO-Career-Portal/SCP-Backend#login)) and check whether it works similarly to register and login users who are registered.
Show popover(not alert) if values are incorrect. Save user session(already done) you can save name or email in session if you want.
Also, make required changes for logout just a request apart from deleting session will so so.

### LINKED ISSUE #24: Reset Password
Make a link for Reset password in Profile page or its dropdown. That will redirect us to the reset password page where user is asked for roll number. After that reset password mail will be sent. Design that reset password page as well. (GO to register PR if needed similar task is done there).
Some links for API you need to work upon.[#1](https://github.com/SPO-Career-Portal/SCP-Backend#reset-password-email) [#2](https://github.com/SPO-Career-Portal/SCP-Backend#reset-password)

### PR DESCRIPTION
**Pull request by uditpd3000**

### CODE REVIEW

File: src/actions/userActions.js [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import { sessionService } from "redux-react-session";
 import axios from "axios";
+import { post } from "jquery";
```
Comment (mridul911) [inline src/actions/userActions.js]: if not using this remove please

File: src/layouts/Admin.js [hunk 2]
```diff
@@ -48,7 +48,17 @@ const Admin = (props) => {
     }
     return "Brand";
   };
-  if (!session.authenticated) {
+  
+  const checkRedirect =() =>{
+    if(props.location.pathname.slice(0,20)=="/user/resetpass/code"){
```
Comment (mridul911) [inline src/layouts/Admin.js]: can also use compare functions in string.

File: src/views/examples/Profile.js [hunk 3]
```diff
@@ -332,7 +341,14 @@ const Profile = () => {
               onClick={onUpdateProfile}
               size="normal"
               >
-              Save
+              Save 
+            </Button>
+            <Button
+              color="primary"
+              onClick= {handleRoute}
```
Comment (mridul911) [inline src/views/examples/Profile.js]: instead of this you can use href parameter or link in react router.

File: src/views/examples/ResetPassEmail.js [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+const ResetPasswordEmail=()=> {
+
+  const [roll, setRoll] = useState("");
+
+  const onSubmit =async()=> {
+    try{
+      await axios.post(BASE_URL+"/user/resetpassemail/",{
+      roll : roll,
+    })
+    .then(function(response){alert(response.data)})
```
Comment (mridul911) [inline src/views/examples/ResetPassEmail.js]: use arrow function .then((response)=>console.log())

**Review by mridul911 — APPROVED** [review]

**Comment by mridul911** [comment]
@uditpd3000 can you please resolve conflicts.
